### DISCUSSION TITLE
How to switch between themes in ng-zorror library

### DISCUSSION THREAD

**Discussion by jdang67** [NG-ZORRO/ng-zorro-antd#6673] [Q&A]
According to the documentation, ng-zorro has  4 differences  themes.
@import "~ng-zorro-antd/ng-zorro-antd.css";
/*@import "~ng-zorro-antd/ng-zorro-antd.dark.css";*/
/*@import "~ng-zorro-antd/ng-zorro-antd.compact.css";*/
/*@import "~ng-zorro-antd/ng-zorro-antd.aliyun.css";*/

However, I have tried to swap them manually  then restart and only the dark theme shows some effects, the rest does not do anything, 

Any idea how to make the other themes work?

Jdang

**Comment by vthinkxie** [comment]
https://ng.ant.design/docs/customize-theme/en#theme-dynamic-switching

**Reply by trunganhhh** [reply]
i don understand, please idea me sthing else

**Comment by KaranTrivedi** [comment]
Can you please provide a complete app example using this feature? I am having a very hard time building this out based on given documentation.

**Reply by keven-bardales** [reply]
were you able to solve this?

**Reply by ysk3a** [reply]
Anyone able to solve this with the latest Angular version?
I tried in Angular 20 by copying https://github.com/yangjunhan/nz-themes into a Angular 20 project but that seem to error out with
```
 Error evaluating function `color`: Cannot read properties of undefined (reading 'toLowerCase') [plugin angular-less]
```
after adding 
```css
/*app.less*/
.themeMixin({
  :host {
    .sidebar-logo {
      background: @primary-1;
      h1 {
        color: @text-color;
      }
    }

    .app-header {
      background: @layout-header-background;
    }

    .header-trigger {
      color: @text-color;
    }

    .inner-content {
      background: @layout-trigger-background;
    }

    .trigger:hover {
      color: #1890ff;
    }
  }
});
```

Removing the above styles allows ng serve to compile without any errors.
So I tried another example mentioned https://github.com/NG-ZORRO/ng-zorro-antd/discussions/8191 which seems give no errors.
But when I try to copy that forked repo into my own Angular 20 fresh application I still get
```
 Error evaluating function `color`: Cannot read properties of undefined (reading 'toLowerCase') [plugin angular-less]
```
due to that above `.themeMixin(...)` of the styles.
