### ISSUE TITLE
Cant change width of nz-date-picker

### ISSUE THREAD

**Issue by chichujn** [NG-ZORRO/ng-zorro-antd#1614]
## Version

0.7.1

## Environment

Windows 10 64bit, Chrome 66, ng-zorro 0.7.1

## Reproduction link

[https://ng-zorro-antd-setup-zkxsjw.stackblitz.io](https://ng-zorro-antd-setup-zkxsjw.stackblitz.io)

## Steps to reproduce

Change width of nz-date-picker to 100%

## What is expected?

nz-date-picker should stretch to fill parent width, like nz-input-number and nz-select etc.

## What is actually happening?

nz-date-picker keep a fixed width, 174px in test

**Comment by vthinkxie** [comment]
nz-date-picker ::ng-deep .ant-calendar-picker{
        width: 100%;
      }

**Comment by vthinkxie** [comment]
@wilsoncook the wrapper div should not exist at all.

**Comment by IonelLupu** [comment]
@vthinkxie any updates on this? Currently I am manually changing the width of the datepicker like this:
```css
nz-date-picker{
    width: 100%;
    nz-picker{
        width: 100%;
        display: inline-block;
        .ant-calendar-picker{
            width: 100%;
        }
    }
}
```
