### ISSUE TITLE
Message 全局提示   如何设置其距离top的距离位置呢?

### ISSUE THREAD

**Issue by Itherma** [NG-ZORRO/ng-zorro-antd#213]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by thegatheringstorm** [comment]
It doesn't seem possible yet.

**Comment by Itherma** [comment]
oh! thank

**Comment by vthinkxie** [comment]
@Itherma you can overwrite the css
```css
.ant-message {
    font-size: 12px;
    position: fixed;
    z-index: 1010;
    width: 100%;
    top: 16px; // Top Position Here
    left: 0;
    pointer-events: none;
}
```
