### ISSUE TITLE
nz-table   nzWidth not work when content is a word

### ISSUE THREAD

**Issue by lumeng689** [NG-ZORRO/ng-zorro-antd#3117]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-table-nzwdith](https://stackblitz.com/edit/ng-zorro-antd-start-table-nzwdith)

### Steps to reproduce
create a table, and title is a very long string

### What is expected?
nzWidth work

### What is actually happening?
nzWidth not work

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.0.3 |
| Browser | chrome version: 71.0.3578.98 |

---
 add css:  word-break: break-word;    to td?

**Comment by vthinkxie** [comment]
if you want to break all word, you can add the style yourself
```css
.ant-table-tbody>tr>td, .ant-table-thead>tr>th{
  word-break: break-word;
}
```
