### ISSUE TITLE
所有含有[nzColor]属性的组件希望增加[nzClass]属性

### ISSUE THREAD

**Issue by DreamPWJ** [NG-ZORRO/ng-zorro-antd#3244]
## What problem does this feature solve?
[nzColor]填写16进制 ，需要每个地方都要填写 ，有些时候如nz-tag背景是主题色   希望主题色更改而更改  统一定义一个class 使用[nzColor]设置更易于维护和修改

## What does the proposed API look like?
[nzClass]='统一定义的颜色class'

**Comment by HsuanXyz** [comment]
```less
nz-tag.ant-tag {
   &.blue {
      background: blue
   }
}
```
```html
<nz-tag class="blue">Tag 1</nz-tag>
```
