### ISSUE TITLE
nz-drawer: close button is visible though nzVisible is false

### ISSUE THREAD

**Issue by timadevelop** [NG-ZORRO/ng-zorro-antd#4304]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-nz-drawer-close-btn-bug](https://stackblitz.com/edit/ng-zorro-antd-nz-drawer-close-btn-bug)

### Steps to reproduce
- Use nz-drawer

### What is expected?
- Hidden close button when nzVisible is false

### What is actually happening?
- The close button is always visible 

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.4.0 |
| Browser | Chrome 77.0 |

---
Here's a simple fix:
```scss
.ant-drawer-wrapper-body {
  // ....
  position: relative;
}
```
