### ISSUE TITLE
Need example/docs on how to use Nz Carousel with images on different screen sizes

### ISSUE THREAD

**Issue by duongle26** [NG-ZORRO/ng-zorro-antd#5271]
## What problem does this feature solve?
I'm trying to create a basic carousel/image slider using NzCarouselModule. The documentation only shows how to implement the carousel with text as the content. I did add img tag to the content as below:
```
<nz-carousel [nzEffect]="effect">
      <div nz-carousel-content *ngFor="let item of array">
        <img [src]='item' />
      </div>
</nz-carousel>
```
However, when I resize the screen, the aspect ratio of the image is not the same as the original. Instead, the height remains the same while the width is shrunk follow the width of the screen. What I want is both 2 dimension the image keep the original ration and shrink follow the screen'size.
Can you help me?
## What does the proposed API look like?
None

**Comment by mdragossh** [comment]
From my point of view the Documentation is one of the best

And more information in documentation

Can check api
https://ng.ant.design/components/carousel/en#api

Live example on stackblitz
https://stackblitz.com/edit/ng-zorro-antd-start-8dj6lb?embed=1&file=src/app/app.component.html
```html
 <nz-carousel [nzEffect]="scrollx" [nzAutoPlay]="true">
      <div nz-carousel-content *ngFor="let imageUrl of arrayOfImgUrls">
        <img [src]='imageUrl' />
      </div>
</nz-carousel>
```

In your component ts
```typescript
arrayOfImgUrls = ['url1', 'url2', 'url3']
```

**Comment by duongle26** [comment]
Yeah I did know how to implement it. The problem I'm dealing with right row is related to css and styling. I can see from the document that the content of carousel item is set to a fix height, which is make the image not responsive in different screen sizes
```
[nz-carousel-content] {
        text-align: center;
        height: 160px;
        line-height: 160px;
        background: #364d79;
        color: #fff;
        overflow: hidden;
}
```

**Comment by duongle26** [comment]
> From my point of view the Documentation is one of the best
> 
> And more information in documentation
> 
> Can check api
> https://ng.ant.design/components/carousel/en#api
> 
> Live example on stackblitz
> https://stackblitz.com/edit/ng-zorro-antd-start-8dj6lb?embed=1&file=src/app/app.component.html
> 
> ```
>  <nz-carousel [nzEffect]="scrollx" [nzAutoPlay]="true">
>       <div nz-carousel-content *ngFor="let imageUrl of arrayOfImgUrls">
>         <img [src]='imageUrl' />
>       </div>
> </nz-carousel>
> ```
> 
> In your component ts
> 
> ```ts
> arrayOfImgUrls = ['url1', 'url2', 'url3']
> ```

Try to view your stackblitz on a mobile screen. The image is width of the image is resize to fit that screen. I want to keep the orginal ratio.

**Comment by mdragossh** [comment]
> Yeah I did know how to implement it. The problem I'm dealing with right row is related to css and styling. I can see from the document that the content of carousel item is set to a fix height, which is make the image not responsive in different screen sizes
> 
> ```
> [nz-carousel-content] {
>         text-align: center;
>         height: 160px;
>         line-height: 160px;
>         background: #364d79;
>         color: #fff;
>         overflow: hidden;
> }
> ```

you can make responsive by editing you style like this
```css
nz-carousel {
  height: 400px;
  width: 800px;
}

img {
  height: 400px;
  width: 800px;
}

@media only screen and (max-width: 600px) {
  nz-carousel {
    height: 200px;
    width: 400px;
  }

  img {
    height: 200px;
    width: 400px;
  }
}
```

**Comment by duongle26** [comment]
@mdragossh thanks for your solution. How about the case where the width of the image always takes up 100% of the screen's width?

**Comment by mdragossh** [comment]
> @mdragossh thanks for your solution. How about the case where the width of the image always takes up 100% of the screen's width?

if i correct understand / you should find an workaround how to do this
for example one workaround can be (may be bad example but can work in some way) 
```html
<nz-carousel [nzDotPosition]="'left'">
      <div nz-carousel-content *ngFor="let imageUrl of array">
        <div
          class="container"
          [style.background]="'url(' + imageUrl + ')'"
        ></div>
      </div>
    </nz-carousel>
```
and your css

```css
.container {
        background-repeat: no-repeat;
        background-position: center;
        -webkit-background-size: contain;
        -moz-background-size: contain;
        -o-background-size: contain;
        background-size: contain;

        height: 100%;
        width: 100%;
      }
```
