### ISSUE TITLE
zorro 10.0版本 上传图片后缩略图显示不正常

### ISSUE THREAD

**Issue by SuperRichZhao** [NG-ZORRO/ng-zorro-antd#5850]
### Reproduction link
[https://stackblitz.com/edit/angular-buen5s?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-buen5s?file=src/app/app.component.ts)

### Steps to reproduce
10.0 版本更新后问题

### What is expected?
上传后能够正常显示缩略图

### What is actually happening?
显示宽度 100% 图片

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.0.0 |
| Browser | chrome |

**Comment by cipchk** [comment]
a temporary solution, add the following under `styles.less`:

```less
.ant-upload-list-picture-card .ant-upload-list-item {
    display: inline-block;
    width: 104px;
    height: 104px;
    margin: 0 8px 8px 0;
    vertical-align: top;
}
```
