### ISSUE TITLE
Notification - Gets cutoff when viewport width is less than +- 390px

### ISSUE THREAD

**Issue by ReinerRunge** [NG-ZORRO/ng-zorro-antd#5929]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-i8r4vr?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-i8r4vr?file=src/app/app.component.ts)

### Steps to reproduce
Resize the window to be smaller than 390px.

### What is expected?
The notification fits neatly on a smaller screen

### What is actually happening?
The right side of the notification gets cutoff

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.0.0 |
| Browser | Chrome |

**Comment by dylanvdmerwe** [comment]
We fixed this issue with the following:

```css
    .ant-notification-notice {
      width: 360px;
      padding: 16px 24px 16px 16px;
    }
```
