### ISSUE TITLE
建议：保留npm包体style目录

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#595]
## What problem does this feature solve?

`src/components/style` 目录是一个非常重要，因为目录包含了一些ANT DESIGN非常重要参数，比如 `@primary-color` 表示主要关系颜色，这在业务使用中非常常用的。

因此，建议在 npm 包体中，将 style 复制到合适的位置下，这样对于使用 ng-zorro-antd 可以更方便的调用到这些变量，否则若希望项目保持ant design的理念，则需要复制 [style](https://github.com/NG-ZORRO/ng-zorro-antd/tree/master/src/components/style) 目录，同时会有大量这类代码：

app.less:

```less
@import "../../style/index.less";

a { color: @primary-color }
```

这里维护位置以及复制style并不是很好的选择，而若 npm 包体包含 style 目录，则：

app.less:

```less
@import "~ng-zorro-antd/style/index.less";

a { color: @primary-color }
```

不管在哪个位置下，我都只需要以 `~ng-zorro-antd` 开头，且无需要维护 style 目录。

## What does the proposed API look like?

npm 包体包含 style 目录
