### ISSUE TITLE
Ng Zorro Modal Title & Content font Size

### ISSUE THREAD

**Issue by ownedbypeli** [NG-ZORRO/ng-zorro-antd#5955]
## What problem does this feature solve?
Could it be possible to add something that you cann change the font size of the title and content in a modal?

## What does the proposed API look like?
nzTitle: {
text:
size:
}

**Comment by hsuanxyz** [comment]
You can use the `nzClassName` property to add a class-name for your modal and then customize the style in css.

```ts
const modal = this.modal.create({
  nzTitle: "Modal Title",
  nzClassName: "my-modal",
  nzContent: NzModalCustomComponent,
  nzViewContainerRef: this.viewContainerRef
});
```

```css
::ng-deep .my-modal .ant-modal-title {
  font-size: 24px;
}
```

https://stackblitz.com/edit/angular-lb2szv?file=src/app/app.component.ts

**Comment by ownedbypeli** [comment]
And the icon size in that case? Do you have any doc for this

**Comment by hsuanxyz** [comment]
Sorry, there is no specific documentation for this. 
Usually we use Chrome DevTools to find the classname of some elements and override their styles in css

**Comment by ownedbypeli** [comment]
So i assume that ant-modal-content is the one for the text

but what is the right one for icon size of the error icon
@hsuanxyz

**Comment by hsuanxyz** [comment]
Do you mean the close icon?  `.ant-modal-close-x`

**Comment by ownedbypeli** [comment]
![grafik](https://user-images.githubusercontent.com/36076242/96845416-f973ff00-1450-11eb-9da5-6161804cda02.png)
is that the close icon?

**Comment by ownedbypeli** [comment]
for me 
::ng-deep .my-modal .ant-modal-title {
  font-size: 24px;
}
does nothing

Are you sure?

**Comment by hsuanxyz** [comment]
```css
// title
::ng-deep .my-modal .ant-modal-confirm-title {
  font-size: 24px;
}

// icon
::ng-deep .my-modal .ant-modal-confirm-body > .anticon {
  ont-size: 24px;
}
```

You can use Chrome DevTools to find the classname

![image](https://user-images.githubusercontent.com/22736418/96896520-2dd2d400-14c0-11eb-9156-9751586c07e0.png)
