### ISSUE TITLE
Menu  应增加一个CollapsedWidth

### ISSUE THREAD

**Issue by zerommc** [NG-ZORRO/ng-zorro-antd#6652]
## What problem does this feature solve?
当设置了Sider 的CollapsedWidth 时，无法与Menu   的宽度匹配，只能通过  重写 .ant-menu-inline-collapsed 的宽度 属性解决

## What does the proposed API look like?
建议增加Menu  的属性CollapsedWidth

**Comment by wenqi73** [comment]
Will fixed after sync this less:
```css
.ant-layout-sider-children .ant-menu.ant-menu-inline-collapsed {
  width: auto;
}
```
