### ISSUE TITLE
[nz-date-picker][regression] Validation feedback (✅) is outside the component

### ISSUE THREAD

**Issue by snebjorn** [NG-ZORRO/ng-zorro-antd#6653]
### Reproduction link
[https://stackblitz.com/edit/angular-3ie7pr?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-3ie7pr?file=src/app/app.component.ts)

### Steps to reproduce
- open stackblitz link
- choose a date
- observe the ✅ is outside the component

### What is expected?
Validation feedback (✅) is inside the component, like this

![image](https://user-images.githubusercontent.com/1266245/116091341-0219ec00-a6a5-11eb-8591-806ec6bae0d7.png)

### What is actually happening?
Validation feedback (✅) is outside the component

![image](https://user-images.githubusercontent.com/1266245/116091202-e6aee100-a6a4-11eb-9eed-1b2c1bc2dc1d.png)

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.4.1 |
| Browser | Chrome |

---
This is a regression as this was working as expected in v8.5

Screenshot from v8.5
![image](https://user-images.githubusercontent.com/1266245/116091633-50c78600-a6a5-11eb-89f4-14d2f2d3e96f.png)

**Comment by wenqi73** [comment]
Add style 
```css
nz-date-picker {
  width: 100%;
}
```

**Comment by snebjorn** [comment]
I see the [documentation](https://ng.ant.design/components/form/en#components-form-demo-validate-static) have been updated to include the various pickers, thanks.

```less
nz-date-picker ::ng-deep .ant-calendar-picker {
  width: 100%;
}

nz-date-picker,
nz-time-picker {
  width: 100%;
}
```

Though I was hoping this could be fixed so it worked "out of the box" instead of having to apply custom styles.
