### ISSUE TITLE
隐藏 nz-input-number 中的 stepper

### ISSUE THREAD

**Issue by hydra1983** [NG-ZORRO/ng-zorro-antd#6796]
## What problem does this feature solve?
当 input 宽度较窄的时候，stepper 会影占用大部分宽度，从而导致数据录入不便捷。因此，希望有组件有属性能控制 stepper 的显隐。

## What does the proposed API look like?
```html
<nz-input-number [nzShowStepper]="false"></nz-input-number>
```<!-- generated by ng-zorro-issue-helper. DO NOT REMOVE -->

**Comment by hydra1983** [comment]
一个临时解决方案：[How TO - Hide Arrows From Input Number](https://www.w3schools.com/howto/howto_css_hide_arrow_number.asp)

```css
/* Chrome, Safari, Edge, Opera */
input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
  -webkit-appearance: none;
  margin: 0;
}

/* Firefox */
input[type=number] {
  -moz-appearance: textfield;
}
```
