### ISSUE TITLE
table只有一列固定在最左侧的话，如果内容过长，加上nzEllipsis指令样式失效

### ISSUE THREAD

**Issue by huajian123** [NG-ZORRO/ng-zorro-antd#7002]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-1plqzh?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-1plqzh?file=src/app/app.component.ts)

### Steps to reproduce
1：设置thead中第一个th的属性为[nzEllipsis]="true"和nzLeft，其余不设置这两个属性。<br>
2：将第一个th中的内容复制多个已致超出表格宽度。<br>
3：将tbody中的第一个td的属性设置为[nzEllipsis]="true" nzLeft>，其余的td不设置这两个属性<br>
4：将第一个td的内容复制多个已致超出表格宽度。 

### What is expected?
第一列固定在最左侧，并且超出的内容以“...”的形式省略。

### What is actually happening?
超出部分不能被省略。

| Environment | Info |
|---|---|
| ng-zorro-antd | 12.0.1 |
| Browser | chrome |

**Comment by simplejason** [comment]
You can change the default styles of table in your style file to avoid it, thanks your report.
```css
.ant-table-cell-ellipsis.ant-table-cell-fix-left-last, .ant-table-cell-ellipsis.ant-table-cell-fix-right-first {
    overflow: hidden;
}
```
