### ISSUE TITLE
position fixed desactive all element when I open modal

### ISSUE THREAD

**Issue by foch01** [NG-ZORRO/ng-zorro-antd#7365]
### Reproduction link
[https://stackblitz.com/edit/angular-tgymql](https://stackblitz.com/edit/angular-tgymql)

### Steps to reproduce
When we have elements in `position: fixed`.

When the modal is opened, this property is deactivated on all elements in fixed position and are therefore no longer visible in the background.

### What is expected?
The background page is not modified

### What is actually happening?
The position: fixed CSS property is no longer applied.

Elements appear at the top of the page when scrolling

| Environment | Info |
|---|---|
| ng-zorro-antd | 13.1.1 |
| Browser | Chrome |

**Comment by volvachev** [comment]
Hi, I have looked into your problem. The `ng-zorro` uses `angular cdk`, when you create a dialog in it `scrollStrategy` is set to `block` by default. 

At the moment there is no way to change this behaviour, perhaps in the future maintainers will have some thoughts on whether to do so.

To solve your problem, you can apply these styles, they will fix your behaviour. (They must be `global`, or a component with `ViewEncapsulation.None`).

```css
.cdk-global-scrollblock {
  position: static !important;
  width: initial !important;
  overflow-y: inherit !important;
}
```

**Comment by justtice-ankomah** [comment]
YES that fixed my issue

> Hi, I have looked into your problem. The `ng-zorro` uses `angular cdk`, when you create a dialog in it `scrollStrategy` is set to `block` by default.
> 
> At the moment there is no way to change this behaviour, perhaps in the future maintainers will have some thoughts on whether to do so.
> 
> To solve your problem, you can apply these styles, they will fix your behaviour. (They must be `global`, or a component with `ViewEncapsulation.None`).
> 
> ```css
> .cdk-global-scrollblock {
>   position: static !important;
>   width: initial !important;
>   overflow-y: inherit !important;
> }
> ```

yes thanks a lot that fixed my issue

**Comment by sedward-ces** [comment]
Its ng-zorro-antd v17. And still this is the workaround for this issue. Its not mentioned anywhere else in the document. maybe this should be linked in the documentation.

**Comment by MarianoFranzese** [comment]
In my case, as I also needed to block the scroll below anyway, I added this to the global style (in scss):

```css
.cdk-global-scrollblock {
  position: static !important;
  width: initial !important;
  overflow-y: inherit !important;

  body {
    overflow: hidden !important;
  }
}
```
