### ISSUE TITLE
how to change menu svg icon font size？

### ISSUE THREAD

**Issue by zengkid** [NG-ZORRO/ng-zorro-antd#9115]
### Reproduction link
[https://stackblitz.com/~/github.com/zengkid/menu-icon](https://stackblitz.com/~/github.com/zengkid/menu-icon)

### Steps to reproduce
I have create custom svg icon for menu, the default menu icon size is 14px, how to change the menu icon font size?
below is the menu code sample.

```javascript
  <li nz-submenu class="menuitem"
      [nzPaddingLeft]="menu.level * 24"
      [nzOpen]="menu.open"
      [nzTitle]="menu.label"
      [nzIcon]="menu.icon"
      [nzDisabled]="menu.disabled"
  >
```

below css didn't change the men icon size with below css
```css
.menuitem > div > nz-icon {
  font-size: 24px;
}
```

### What is expected?
able to change menu icon size.

### What is actually happening?
menu icon size unabel to change

| Environment | Info |
|---|---|
| ng-zorro-antd | 19.2.2 |
| Browser | edge |

**Comment by ParsaArvanehPA** [comment]
Hi @zengkid,
Since styles in Angular are by default encapsulated, you need to use `::ng-deep` to handle this task.
Somehting like this 👇

app.component.scss:
```scss
:host {
  ::ng-deep {
    .ant-menu {
      .menuitem {
        svg {
          font-size: 24px;
        }
      }
    }
  }
}
```
