### ISSUE TITLE
nz-table custom column cannot use resizable table header normally

### ISSUE THREAD

**Issue by lanxuexing** [NG-ZORRO/ng-zorro-antd#9137]
### Reproduction link
[https://stackblitz.com/edit/pc13jjnz-y53wnwrt](https://stackblitz.com/edit/pc13jjnz-y53wnwrt)

### Steps to reproduce
1. Enable column resizing on the table header.
2. Try dragging the resize handle to the left – the preview shows up as expected.
3. Try dragging the resize handle to the right – the preview does not show up or behaves incorrectly.

### What is expected?
The nz-resizable-preview indicator should display properly both when dragging to the left and to the right.

### What is actually happening?
The preview indicator only works when dragging to the left, but does not work (or does not show up) when dragging to the right.

| Environment | Info |
|---|---|
| ng-zorro-antd | 19.3.1 |
| Browser | Google Chrome 136.0.7103.114  (x86_64) |

**Comment by lanxuexing** [comment]
Temporary workaround: Adding styles inside the component using :host and ::ng-deep works for me:
```scss
:host {
  .nz-resizable-preview {
    border-width: 0;
    border-right-width: 1px;
  }

  ::ng-deep {
    .ant-table-custom-column:has(.nz-resizable-preview) {
      .ant-table-thead tr th {
        overflow: inherit;
      }
    }
  }
}
```
However, I hope this can be supported by the component natively, without relying on deep/global CSS hacks.
